import java.util.ArrayList;
import java.util.Stack;

public class Main {

    public static Stack<card> pile = new Stack<>();
    public static ArrayList<card> deck = new ArrayList<>();
    public static void main(String[] args) {
        /**
         * initialize all 81 cards
         */
        card c1 = new card(1, "r", "opn", "dmd", "src/images/row-1-column-1.png");
        card c2 = new card(2, "r", "opn", "dmd", "src/images/row-1-column-2.png");
        card c3 = new card(3, "r", "opn", "dmd", "src/images/row-1-column-3.png");
        card c4 = new card(1, "r", "opn", "ovl", "src/images/row-1-column-4.png");
        card c5 = new card(2, "r", "opn", "ovl", "src/images/row-1-column-5.png");
        card c6 = new card(3, "r", "opn", "ovl", "src/images/row-1-column-6.png");
        card c7 = new card(1, "r", "opn", "squ", "src/images/row-1-column-7.png");
        card c8 = new card(2, "r", "opn", "squ", "src/images/row-1-column-8.png");
        card c9 = new card(3, "r", "opn", "squ", "src/images/row-1-column-9.png");
        card c10 = new card(1, "r", "str", "dmd", "src/images/row-2-column-1.png");
        card c11 = new card(2, "r", "str", "dmd", "src/images/row-2-column-2.png");
        card c12 = new card(3, "r", "str", "dmd", "src/images/row-2-column-3.png");
        card c13 = new card(1, "r", "str", "ovl", "src/images/row-2-column-4.png");
        card c14 = new card(2, "r", "str", "ovl", "src/images/row-2-column-5.png");
        card c15 = new card(3, "r", "str", "ovl", "src/images/row-2-column-6.png");
        card c16 = new card(1, "r", "str", "squ", "src/images/row-2-column-7.png");
        card c17 = new card(2, "r", "str", "squ", "src/images/row-2-column-8.png");
        card c18 = new card(3, "r", "str", "squ", "src/images/row-2-column-9.png");
        card c19 = new card(1, "r", "sol", "dmd", "src/images/row-3-column-1.png");
        card c20 = new card(2, "r", "sol", "dmd", "src/images/row-3-column-2.png");
        card c21 = new card(3, "r", "sol", "dmd", "src/images/row-3-column-3.png");
        card c22 = new card(1, "r", "sol", "ovl", "src/images/row-3-column-4.png");
        card c23 = new card(2, "r", "sol", "ovl", "src/images/row-3-column-5.png");
        card c24 = new card(3, "r", "sol", "ovl", "src/images/row-3-column-6.png");
        card c25 = new card(1, "r", "sol", "squ", "src/images/row-3-column-7.png");
        card c26 = new card(2, "r", "sol", "squ", "src/images/row-3-column-8.png");
        card c27 = new card(3, "r", "sol", "squ", "src/images/row-3-column-9.png");
        card c28 = new card(1, "g", "opn", "dmd", "src/images/row-4-column-1.png");
        card c29 = new card(2, "g", "opn", "dmd", "src/images/row-4-column-2.png");
        card c30 = new card(3, "g", "opn", "dmd", "src/images/row-4-column-3.png");
        card c31 = new card(1, "g", "opn", "ovl", "src/images/row-4-column-4.png");
        card c32 = new card(2, "g", "opn", "ovl", "src/images/row-4-column-5.png");
        card c33 = new card(3, "g", "opn", "ovl", "src/images/row-4-column-6.png");
        card c34 = new card(1, "g", "opn", "squ", "src/images/row-4-column-7.png");
        card c35 = new card(2, "g", "opn", "squ", "src/images/row-4-column-8.png");
        card c36 = new card(3, "g", "opn", "squ", "src/images/row-4-column-9.png");
        card c37 = new card(1, "g", "str", "dmd", "src/images/row-5-column-1.png");
        card c38 = new card(2, "g", "str", "dmd", "src/images/row-5-column-2.png");
        card c39 = new card(3, "g", "str", "dmd", "src/images/row-5-column-3.png");
        card c40 = new card(1, "g", "str", "ovl", "src/images/row-5-column-4.png");
        card c41 = new card(2, "g", "str", "ovl", "src/images/row-5-column-5.png");
        card c42 = new card(3, "g", "str", "ovl", "src/images/row-5-column-6.png");
        card c43 = new card(1, "g", "str", "squ", "src/images/row-5-column-7.png");
        card c44 = new card(2, "g", "str", "squ", "src/images/row-5-column-8.png");
        card c45 = new card(3, "g", "str", "squ", "src/images/row-5-column-9.png");
        card c46 = new card(1, "g", "sol", "dmd", "src/images/row-6-column-1.png");
        card c47 = new card(2, "g", "sol", "dmd", "src/images/row-6-column-2.png");
        card c48 = new card(3, "g", "sol", "dmd", "src/images/row-6-column-3.png");
        card c49 = new card(1, "g", "sol", "ovl", "src/images/row-6-column-4.png");
        card c50 = new card(2, "g", "sol", "ovl", "src/images/row-6-column-5.png");
        card c51 = new card(3, "g", "sol", "ovl", "src/images/row-6-column-6.png");
        card c52 = new card(1, "g", "sol", "squ", "src/images/row-6-column-7.png");
        card c53 = new card(2, "g", "sol", "squ", "src/images/row-6-column-8.png");
        card c54 = new card(3, "g", "sol", "squ", "src/images/row-6-column-9.png");
        card c55 = new card(1, "p", "opn", "dmd", "src/images/row-7-column-1.png");
        card c56 = new card(2, "p", "opn", "dmd", "src/images/row-7-column-2.png");
        card c57 = new card(3, "p", "opn", "dmd", "src/images/row-7-column-3.png");
        card c58 = new card(1, "p", "opn", "ovl", "src/images/row-7-column-4.png");
        card c59 = new card(2, "p", "opn", "ovl", "src/images/row-7-column-5.png");
        card c60 = new card(3, "p", "opn", "ovl", "src/images/row-7-column-6.png");
        card c61 = new card(1, "p", "opn", "squ", "src/images/row-7-column-7.png");
        card c62 = new card(2, "p", "opn", "squ", "src/images/row-7-column-8.png");
        card c63 = new card(3, "p", "opn", "squ", "src/images/row-7-column-9.png");
        card c64 = new card(1, "p", "str", "dmd", "src/images/row-8-column-1.png");
        card c65 = new card(2, "p", "str", "dmd", "src/images/row-8-column-2.png");
        card c66 = new card(3, "p", "str", "dmd", "src/images/row-8-column-3.png");
        card c67 = new card(1, "p", "str", "ovl", "src/images/row-8-column-4.png");
        card c68 = new card(2, "p", "str", "ovl", "src/images/row-8-column-5.png");
        card c69 = new card(3, "p", "str", "ovl", "src/images/row-8-column-6.png");
        card c70 = new card(1, "p", "str", "squ", "src/images/row-8-column-7.png");
        card c71 = new card(2, "p", "str", "squ", "src/images/row-8-column-8.png");
        card c72 = new card(3, "p", "str", "squ", "src/images/row-8-column-9.png");
        card c73 = new card(1, "p", "sol", "dmd", "src/images/row-9-column-1.png");
        card c74 = new card(2, "p", "sol", "dmd", "src/images/row-9-column-2.png");
        card c75 = new card(3, "p", "sol", "dmd", "src/images/row-9-column-3.png");
        card c76 = new card(1, "p", "sol", "ovl", "src/images/row-9-column-4.png");
        card c77 = new card(2, "p", "sol", "ovl", "src/images/row-9-column-5.png");
        card c78 = new card(3, "p", "sol", "ovl", "src/images/row-9-column-6.png");
        card c79 = new card(1, "p", "sol", "squ", "src/images/row-9-column-7.png");
        card c80 = new card(2, "p", "sol", "squ", "src/images/row-9-column-8.png");
        card c81 = new card(3, "p", "sol", "squ", "src/images/row-9-column-9.png");

        deck.add(c1);
        deck.add(c2);
        deck.add(c3);
        deck.add(c4);
        deck.add(c5);
        deck.add(c6);
        deck.add(c7);
        deck.add(c8);
        deck.add(c9);
        deck.add(c10);
        deck.add(c11);
        deck.add(c12);
        deck.add(c13);
        deck.add(c14);
        deck.add(c15);
        deck.add(c16);
        deck.add(c17);
        deck.add(c18);
        deck.add(c19);
        deck.add(c20);
        deck.add(c21);
        deck.add(c22);
        deck.add(c23);
        deck.add(c24);
        deck.add(c25);
        deck.add(c26);
        deck.add(c27);
        deck.add(c28);
        deck.add(c29);
        deck.add(c30);
        deck.add(c31);
        deck.add(c32);
        deck.add(c33);
        deck.add(c34);
        deck.add(c35);
        deck.add(c36);
        deck.add(c37);
        deck.add(c38);
        deck.add(c39);
        deck.add(c40);
        deck.add(c41);
        deck.add(c42);
        deck.add(c43);
        deck.add(c44);
        deck.add(c45);
        deck.add(c46);
        deck.add(c47);
        deck.add(c48);
        deck.add(c49);
        deck.add(c50);
        deck.add(c51);
        deck.add(c52);
        deck.add(c53);
        deck.add(c54);
        deck.add(c55);
        deck.add(c56);
        deck.add(c57);
        deck.add(c58);
        deck.add(c59);
        deck.add(c60);
        deck.add(c61);
        deck.add(c62);
        deck.add(c63);
        deck.add(c64);
        deck.add(c65);
        deck.add(c66);
        deck.add(c67);
        deck.add(c68);
        deck.add(c69);
        deck.add(c70);
        deck.add(c71);
        deck.add(c72);
        deck.add(c73);
        deck.add(c74);
        deck.add(c75);
        deck.add(c76);
        deck.add(c77);
        deck.add(c78);
        deck.add(c79);
        deck.add(c80);
        deck.add(c81);

        new coverPage().setVisible(true);
    }
}
